### ISSUE TITLE
求完善layout转

### ISSUE THREAD

**Issue by lozn00** [SickWorm/AndroidXMLToJava#2]
跪求哈。。

**Comment by sickworm** [comment]
hello，你可以把不支持的属性发出来，或者直接提供你测试的demo给我~

**Comment by lozn00** [comment]
能不能把基本的 layout/xml文件转换为java代码呢。  这样方便方便一些，
为什么我要这样弄呢、
因为我在逆向的时候 xml没法注入 只能破dex文件 所以呢 我可以在android studio写好xml，然后用工具直接生成java,。这样效率肯定高一些，看了一下android源码 懵逼，感觉反射也没法解决，不知道大神能不能研究出来把字符串本地，网络 xml变成java代码或者 研究layout.inflate代码，弄成和Layout.from一样的效果返回一个view布局。填充进去。

**Comment by sickworm** [comment]
之前有做了一点，但没有提交，我刚刚提交了。
现在你可以通过运行gui包下的MainEntry.java启动一个简单的GUI界面进行翻译。或者调用 ContentConverter.java进行通过传入参数进行翻译。不过要注意的是：如果你的xml依赖了其他资源，事情就没那么简单了。所以我一开始只做了整个project的转换。

**Comment by sickworm** [comment]
关于你的需求，我觉得你不如直接用Java代码写好了。
此外我之前阅读过的这个文章：http://blog.csdn.net/lmj623565791/article/details/53370414
你可以参考一下，如何把资源（布局文件）打包进去

**Comment by lozn00** [comment]
e嗯 ，我逆向的不是简单的 那种，是xml文件被严重捣腾过的，apktool解决不了问题哈所以 。

**Comment by lozn00** [comment]
大神是用啥东西上传github啊我折下载都很慢估计上传更慢了，你那文件几k每秒 ，我也不知道翻墙收费软件到底能不能解决问题如果能解决我觉得花几百块钱也无所谓了。

**Comment by sickworm** [comment]
电信网络直连。。不翻
